# Generated by Django 4.2.2 on 2023-06-09 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0004_alter_reservation_car_alter_reservation_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 10, 19, 49, 58, 572438, tzinfo=datetime.timezone.utc)),
        ),
    ]
