# Generated by Django 4.2.2 on 2023-06-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0006_query_alter_reservation_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='car',
            field=models.ManyToManyField(to='rentacar.car'),
        ),
    ]
