# Generated by Django 4.2.2 on 2023-06-10 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0007_query_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='car',
            new_name='available_cars',
        ),
    ]
