# Generated by Django 4.2.1 on 2023-05-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.IntegerField(),
        ),
    ]
