version: "1.0"

services:

  frontend:
    image: "frontend"
    build: ./frontend
    ports:
      - 3000:3000
      - 80:3000
    restart: on-failure
    depends_on:
      - backend

  backend:
    image: "backend"
    build: ./backend
    ports:
      - 8000:8000
      - 8080:8000
    restart: on-failure
    volumes:
    - $PWD/backend/db.sqlite3:/backend/db.sqlite3